name: license-check

on:
  repository_dispatch:
    types: [org-workflow-bot]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }} # Default: name of workflow. This name is shown with the check, but can be changed.
        documentation: https://github.com/Cray-HPE/license-checker

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.repository.full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}

    - name: License Check
      id: license_check
      uses: docker://artifactory.algol60.net/csm-docker/stable/license-checker:latest
      continue-on-error: true

    - name: Debug steps
      env:
        STEPS_OUTCOME: ${{ steps.license_check.outcome }}
      run: printenv | sort

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"

    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Report license check result
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api -X POST repos/${{ github.event.client_payload.repository.full_name }}/statuses/${{ github.event.client_payload.sha }} \
            -f state=${{ steps.license_check.outcome }}
            -f context=license-check
            -f description=${{ steps.license_check.outcome }}
            -f target_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}